name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11.5
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install CMake
      run: choco install cmake -y
  
    - name: Install dependencies for Visual Studio Build Tools
      run: choco install chocolatey-dotnetfx.extension -y
  
    - name: Install Visual Studio Build Tools
      run: choco install visualstudio2022buildtools -y --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
  
  

    - name: Install Python dependencies
      run: python -m pip install -r requirements.txt

    - name: Run build script
      shell: bash
      run: ./build-all.sh
