name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11.5
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

    - name: Install Visual Studio Build Tools
      uses: egor-tensin/setup-msvc@v1
      with:
        vs-version: 17.0

    - name: Install Python dependencies
      run: python -m pip install -r requirements.txt

    - name: Run build script
      shell: bash
      run: ./build-all.sh

